# This file contains values from Cookiecutter

default_context:
  project_name: "gathering"
  project_plug: "gathering"
  project_description: "gathering for gathering information"
  organization: "fluent-qa"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "qdriven"
  email: "hello@fluent-qa.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "server"
